# Generated by Django 5.0.6 on 2024-06-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_apicall_document_alter_apicall_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
